"""
Django settings for globexy project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'x6!dxgw@5+v_9f^$ce!2#=xg!y1a99@%&z7vjk&f5)u-fn)zif'
SERVER_ID = "584776fc3f115a3398d82ead"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'oauth2_provider',

    'api',
    'user',
    'utils',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Save the session_id in thread local data for using it for access to tokens
    'user.middleware.SaveSessionIdMiddleware',
    'user.middleware.AnonimousUserLoginMiddleware',
]

ROOT_URLCONF = 'globexy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_settings_export.settings_export',
            ],
        },
    },
]

WSGI_APPLICATION = 'globexy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


POLYMER_GUI = '../polymer'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    POLYMER_GUI,
]

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

AUTHENTICATION_BACKENDS = [
    'user.backends.AuthServerBackend',
    'django.contrib.auth.backends.ModelBackend'
]
AUTH_USER_MODEL = "user.User"
# LOGIN_URL = '/user/login/'
LOGIN_REDIRECT_URL = 'None'
LOGOUT_REDIRECT_URL = 'None'

AUTH_SERVER = 'ws://192.168.10.66:48081'
RC_SERVER = 'ws://192.168.10.66:48080'
SCRIPT_SERVER = 'ws://192.168.10.66:48078'

SETTINGS_EXPORT = [
    'AUTH_SERVER',
    'RC_SERVER',
    'SCRIPT_SERVER',
]

SESSION_COOKIE_AGE = 60 * 60 * 24 * 7 * 2

SESSION_ENGINE = 'redis_sessions.session'
SESSION_REDIS_HOST = 'localhost'
SESSION_REDIS_PORT = 6379
SESSION_REDIS_DB = 0
# SESSION_REDIS_PASSWORD = 'password'
SESSION_REDIS_PREFIX = 'session'
SESSION_REDIS_SOCKET_TIMEOUT = 1

ANONYMOUS_USER_NAME = "AnonymousUser"
ANONYMOUS_USER_PASS = "SuperSicretPassword"

try:
    from globexy.settings_local import *
except ImportError:
    print('Create local settings module before start the project. Use "settings_local.py.sample" as template.')
    exit(1)
